### ISSUE TITLE
engine-nunjucks

### ISSUE THREAD

**Issue by jonschlinkert** [airtonix/template-nunjucks#1]
@airtonix are you still planning to use engine-nunjucks? thanks!

**Comment by airtonix** [comment]
@jonschlinkert can you clarify what you mean?

**Comment by jonschlinkert** [comment]
You published both engine-nunjucks and template-nunjucks, but template-nunjucks is more updated it looks like.

**Comment by jonschlinkert** [comment]
ping, would you mind releasing engine-nunjucks on npm since there isn't a repo or code?

**Comment by airtonix** [comment]
@jonschlinkert sure thing, tell me exactly what to do: 

Something like?

```
~/Projects/template-nunjucks $ npm owner jonschlinkert
```

**Comment by airtonix** [comment]
nvm... done: 

```
$ npm login
username: ...
password: ...
email: ...

$ npm unpublish engine-nunjucks --force
```

**Comment by jonschlinkert** [comment]
thanks!
